<?php
/**
 * @file
 * Code for the Camp News Import feature.
 */

include_once 'camp_news_import.features.inc';

/**
 * Implements hook_feeds_plugins()
 */
function camp_news_import_feeds_plugins() {
  $info = array();
  $info['camp_news_parser'] = array(
    'name' => 'Drupal Camp News XML feed parser',
    'description' => 'Imports Drupal Camp stories XML feed.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser', // Being directly or indirectly an extension of FeedsParser makes a plugin a parser plugin.
      'class' => 'CampNewsXmlParser',
      'file' => 'camp_news_parser.inc',
      'path' => drupal_get_path('module', 'camp_news_import') . '/plugins/feeds',
    ),
  );
  return $info;
}